# Generated by Django 2.2.28 on 2022-11-13 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_addresszhiszcdxzb'),
    ]

    operations = [
        migrations.AddField(
            model_name='addresszhiszcdxzb',
            name='ca',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
